const themeLoader = document.createElement('script');
themeLoader.src = '../theme.js';
document.head.append(themeLoader);

const GRADE_DATA = {
  1: { level: 'BEGINNER', title: 'First sounds', subtitle: 'Get comfortable with the guitar, make two clear chords, and find a steady beat.', outcomes: ['Tune the six open strings', 'Play Em and Am cleanly', 'Count a steady 4/4 pulse'], lessons: [
    { title: 'Your guitar & the open strings', label: 'SETUP', text: 'Learn the headstock, tuners, neck, frets and body. Tune from the thick low E to the thin high E: E–A–D–G–B–E.', visual: 'E · A · D · G · B · E', visualNote: 'standard tuning · low to high', practice: 'Tune one string at a time; name each string as you pluck it.' },
    { title: 'Two first chord shapes', label: 'CHORDS', text: 'Em is E–G–B; Am is A–C–E. A minor lowers the third of A major by one semitone. Fret close behind each fret wire.', visual: 'Em   ↔   Am', visualNote: 'E–G–B      A–C–E', practice: 'Pick every string separately, then change between the two shapes four times.', chord: 'Em' },
    { title: 'Count before you strum', label: 'RHYTHM', text: 'Tap your foot on beats 1, 2, 3, 4. Keep the strumming arm loose and make one quiet downstroke per beat.', visual: '1   2   3   4', visualNote: 'four even downstrokes', practice: 'Count aloud while strumming muted strings for one minute.' },
    { title: 'Make a tiny practice loop', label: 'PRACTICE', text: 'A short routine builds relaxed, repeatable movement. Stop when your hand tenses; shake it out and reset.', visual: 'TUNE → SHAPE → STRUM', visualNote: 'one small win at a time', practice: 'Play Em for four beats, Am for four beats, and repeat for two minutes.' }
  ] },
  2: { level: 'BEGINNER', title: 'Open-chord family', subtitle: 'Add C, G and D, then practise changing shapes without losing the beat.', outcomes: ['Form C, G and D', 'Change chords on beat one', 'Play a simple eighth-note pulse'], lessons: [
    { title: 'C, G and D shapes', label: 'CHORDS', text: 'These open-position shapes use a mix of fretted and ringing strings. C is C–E–G, G is G–B–D, and D is D–F♯–A.', visual: 'C · G · D', visualNote: 'three notes make a triad', practice: 'Build each shape slowly, then check each string for buzzes.', chord: 'C' },
    { title: 'The anchor-finger change', label: 'MOVEMENT', text: 'Notice which fingers stay near the strings between G and D. Move only the fingers that need to travel; avoid lifting high.', visual: 'G   ⇄   D', visualNote: 'small motion, steady pulse', practice: 'One bar per chord at 50 BPM; raise tempo only after four clean loops.' },
    { title: 'Down and up motion', label: 'RHYTHM', text: 'Count “1 & 2 & 3 & 4 &”. Keep the hand moving down on numbers and up on “and”; begin with a light touch.', visual: '↓   ↑   ↓   ↑', visualNote: '1 & 2 &', practice: 'Mute the strings first and make eight equal movements per bar.' },
    { title: 'First two-chord songs', label: 'SONGS', text: 'Choose a song that uses shapes you already know. Make the chord change at the same point every time, even if the first pass is slow.', visual: 'Em   ·   G   ·   D', visualNote: 'listen for the change', practice: 'Loop a verse progression with a metronome at a comfortable tempo.' }
  ] },
  3: { level: 'BEGINNER', title: 'Play complete songs', subtitle: 'Turn a chord collection into music with changing strums, common progressions and basic picking.', outcomes: ['Use Am, C, D, Dm, Em and G', 'Recognize I–IV–V–vi', 'Pick a simple bass-to-treble pattern'], lessons: [
    { title: 'Chord changes in time', label: 'CHORDS', text: 'Practise the change itself, not only the comfortable shape. Prepare your next fingers during the final beat of each bar.', visual: 'C → G → D → Am', visualNote: 'one bar each', practice: 'Set a slow click and make eight clean changes before increasing speed.', chord: 'Am' },
    { title: 'A four-chord progression', label: 'HARMONY', text: 'In G major, G, C, D and Em are I, IV, V and vi. They share notes with the G major scale, which helps them sound at home together.', visual: 'G  ·  C  ·  D  ·  Em', visualNote: 'I  ·  IV  ·  V  ·  vi', practice: 'Play each chord for four beats; listen for how Em changes the mood.' },
    { title: 'Strum with a lift', label: 'RHYTHM', text: 'Accent beats 2 and 4 softly. Let some upstrokes brush only the thinnest strings to make the groove lighter.', visual: '1  &  2  &  3  &  4  &', visualNote: 'light accents on 2 and 4', practice: 'Clap the accents before adding the guitar.' },
    { title: 'First arpeggio', label: 'PICKING', text: 'Hold Am still and pluck the A, G, B and high E strings in order. Keep the notes even and let each one ring.', visual: 'A → G → B → e', visualNote: 'bass to treble', practice: 'Repeat the pattern slowly for two minutes without changing the chord.' }
  ] },
  4: { level: 'INTERMEDIATE', title: 'Movable chord shapes', subtitle: 'Take familiar major and minor shapes up the neck and learn to keep rhythm under pressure.', outcomes: ['Build E-form and A-form barre chords', 'Locate roots on strings 6 and 5', 'Use muted strums and syncopation'], lessons: [
    { title: 'Barre-chord mechanics', label: 'CHORDS', text: 'The index finger acts like a movable nut. Place it close to the fret wire, roll slightly onto its bony edge, and add the remaining chord tones.', visual: 'E-shape  ↔  A-shape', visualNote: 'same quality, new root', practice: 'Fret one shape for two beats, release pressure without lifting, then repeat.', chord: 'F' },
    { title: 'Roots on the sixth & fifth strings', label: 'FRETBOARD', text: 'Find the note under the barre. The E-form root sits on string 6; the A-form root sits on string 5. The shape name is a fingering map, not the chord name.', visual: '6th string · E form\n5th string · A form', visualNote: 'find the root first', practice: 'Find F, G and A roots on both bass strings.' },
    { title: 'Muted sixteenth accents', label: 'RHYTHM', text: 'Keep the picking hand moving in small, even strokes. Touch the strings lightly with the fretting hand to create a percussive “chuck”.', visual: '1 e & a 2 e & a', visualNote: 'accent one subdivision', practice: 'Mute all strings and accent the “&” of beat 2.' },
    { title: 'CAGED as a map', label: 'VOICINGS', text: 'C, A, G, E and D are five overlapping open-chord reference shapes. Learn how their roots connect; use only the part of each shape that sounds useful.', visual: 'C · A · G · E · D', visualNote: 'five windows, one neck', practice: 'Find one C major shape in two different neck positions.' }
  ] },
  5: { level: 'INTERMEDIATE', title: 'Scales connect to chords', subtitle: 'Use intervals to understand chord quality, map scale tones and target notes that belong to each chord.', outcomes: ['Construct major and minor triads', 'Read major and minor scale formulas', 'Target chord tones while soloing'], lessons: [
    { title: 'The major scale formula', label: 'SCALES', text: 'A major scale follows whole, whole, half, whole, whole, whole, half steps. The formula stays the same in every key; the root changes.', visual: 'W · W · H · W · W · W · H', visualNote: 'W = 2 frets · H = 1 fret', practice: 'Play one octave of G major and say the note names.' },
    { title: 'Why major and minor sound different', label: 'CHORDS', text: 'A triad stacks scale degrees 1, 3 and 5. A major third is four semitones above the root; a minor third is three. That one-semitone change changes the color.', visual: 'C–E–G  →  C–E♭–G', visualNote: 'major 3rd → minor 3rd', practice: 'Compare C and Cm, then name the note that changed.', chord: 'C' },
    { title: 'Diatonic chords in a key', label: 'HARMONY', text: 'Build a triad from each scale degree using every other note. A major key gives the pattern I, ii, iii, IV, V, vi, vii diminished.', visual: 'I · ii · iii · IV · V · vi · vii°', visualNote: 'major · minor · diminished', practice: 'Write the seven triads in C major, then play I–V–vi–IV.' },
    { title: 'Scale notes over changing chords', label: 'IMPROVISATION', text: 'A scale gives the shared palette; chord tones show where each harmony lands. Hold a chord, play its root–3rd–5th, then fill the gaps with nearby scale notes.', visual: 'CHORD TONES + PASSING TONES', visualNote: 'land on 1 · 3 · 5', practice: 'Over Am–F–C–G, end each bar on a note in its chord.' }
  ] },
  6: { level: 'INTERMEDIATE', title: 'Color and motion', subtitle: 'Expand basic triads into seventh chords, arpeggios and rhythms that make progressions move.', outcomes: ['Build four-note seventh chords', 'Play chord tones as arpeggios', 'Use triplets and rests deliberately'], lessons: [
    { title: 'Four-note chord formulas', label: 'CHORDS', text: 'Add the seventh scale degree to a triad. A dominant 7 uses a flattened seventh; a major 7 keeps the major seventh; a minor 7 combines a minor triad and flat seventh.', visual: '7: 1–3–5–♭7', visualNote: 'maj7: 1–3–5–7', practice: 'Compare G7 and Gmaj7; hear how the seventh changes the pull.', chord: 'G' },
    { title: 'Arpeggios as harmony', label: 'PICKING', text: 'Play a chord one note at a time. Track 1, 3, 5 and 7 across nearby strings, then resolve your line to the next chord’s root or third.', visual: '1 → 3 → 5 → ♭7', visualNote: 'outline the chord', practice: 'Arpeggiate Dm7 and G7, then land on C.' },
    { title: 'Triplet pulse', label: 'RHYTHM', text: 'Divide a beat into three equal parts: “1-trip-let”. Keep the subdivision steady before placing accents or skipping a note.', visual: '1-trip-let  2-trip-let', visualNote: 'three equal spaces', practice: 'Tap triplets at a slow tempo; add one muted strum per beat.' },
    { title: 'Minor-key dominant', label: 'HARMONY', text: 'In D natural minor, A is minor. Raising C to C♯ creates A major or A7; C♯ pulls strongly upward to D and gives the cadence direction.', visual: 'Dm → Gm → A7 → Dm', visualNote: 'C♯ resolves to D', practice: 'Play the progression and hum the C♯–D resolution.' }
  ] },
  7: { level: 'ADVANCED', title: 'Make the neck your own', subtitle: 'Connect scale positions with chord tones, use modes intentionally and shape melodic phrases.', outcomes: ['Map triads through CAGED positions', 'Choose modes by harmonic context', 'Build phrases with motif and space'], lessons: [
    { title: 'Triads inside larger shapes', label: 'VOICING', text: 'A full six-string chord contains repeated notes. Find compact 3-note triads on strings 1–3, 2–4 and 3–5 to make clean inversions and chord melodies.', visual: 'ROOT · 3RD · 5TH', visualNote: 'three strings, one voicing', practice: 'Play C major in root, first and second inversion on the top three strings.' },
    { title: 'Modes with a tonal center', label: 'SCALES', text: 'A mode is not just a scale starting on a different note. Establish the tonic chord or drone first, then compare the mode’s characteristic interval against that center.', visual: 'IONIAN · DORIAN · MIXOLYDIAN', visualNote: 'hear the home note', practice: 'Hold a Dm7 drone and compare D Dorian with D natural minor.' },
    { title: 'Phrase with a motif', label: 'MELODY', text: 'A strong solo develops a small rhythmic or melodic idea. Repeat it, vary the ending, and leave space so each answer feels connected.', visual: 'IDEA → REPEAT → ANSWER', visualNote: 'variation gives direction', practice: 'Improvise three phrases using the same rhythm and different notes.' },
    { title: 'Chord melody basics', label: 'ARRANGING', text: 'Keep a melody note on top while choosing compact chord tones underneath. Preserve the melody first; simplify the inner voicing if the grip is awkward.', visual: 'MELODY ON TOP', visualNote: 'voice leading underneath', practice: 'Harmonize a four-note melody using close C major triads.' }
  ] },
  8: { level: 'ADVANCED', title: 'Arrange and expand', subtitle: 'Use extensions, voice leading, alternate feels and arrangement choices to create a richer guitar part.', outcomes: ['Color triads with 9ths and 11ths', 'Voice-lead chord changes smoothly', 'Arrange for dynamics and texture'], lessons: [
    { title: 'Extensions with a purpose', label: 'HARMONY', text: 'Ninths, elevenths and thirteenths add color above the seventh. Choose extensions that support the melody and fit the chord’s function; omit less useful tones when necessary.', visual: '1 · 3 · 5 · 7 · 9', visualNote: 'add color above the triad', practice: 'Compare Cmaj7 and Cmaj9 while holding the same melody note.' },
    { title: 'Voice leading between chords', label: 'VOICING', text: 'Keep common tones in place and move other notes by the smallest interval available. Smooth inner lines can make even a familiar progression feel deliberate.', visual: 'COMMON TONE → SMALL STEP', visualNote: 'listen to each voice', practice: 'Connect Cmaj7 to Am7 using the nearest chord tones.' },
    { title: 'Time feel and subdivision', label: 'RHYTHM', text: 'Choose straight or swung subdivisions to serve the style. Keep the pulse consistent while changing where accents, rests and anticipations sit.', visual: 'STRAIGHT  /  SWUNG', visualNote: 'same pulse, different feel', practice: 'Play one groove straight, then swing the eighth notes without changing BPM.' },
    { title: 'Build an arrangement', label: 'ARRANGING', text: 'Give each section a role: sparse verse, fuller chorus, contrasting bridge. Change register, dynamics or articulation before adding more notes.', visual: 'SPACE → LIFT → CONTRAST', visualNote: 'arrange with intention', practice: 'Arrange one progression in two textures: fingerpicked and strummed.' }
  ] },
  9: { level: 'ADVANCED', title: 'Compose, record, perform', subtitle: 'Bring technique and theory together to write, learn by ear, shape a performance and review your recordings.', outcomes: ['Create a progression with voice leading', 'Transcribe a short musical phrase', 'Record and refine a complete performance'], lessons: [
    { title: 'Write from a musical seed', label: 'COMPOSITION', text: 'Begin with a rhythm, bass movement, melodic fragment or chord color. Develop it into sections by repeating, changing and contrasting the original idea.', visual: 'MOTIF → SECTION → SONG', visualNote: 'develop, do not just add', practice: 'Write an eight-bar piece from a two-bar motif.' },
    { title: 'Reharmonize a melody', label: 'HARMONY', text: 'Identify melody notes that can sit above several possible chords. Keep the melody recognizable while changing bass motion or chord function beneath it.', visual: 'MELODY NOTE + NEW BASS', visualNote: 'preserve the tune', practice: 'Harmonize one simple melody with two different progressions.' },
    { title: 'Learn a phrase by ear', label: 'TRANSCRIPTION', text: 'Sing a short phrase, find its starting pitch, then work out its rhythm and intervals. Verify the notes against the recording rather than relying on hand shapes.', visual: 'SING → FIND → CHECK', visualNote: 'short phrases first', practice: 'Transcribe two bars and play them in a second position.' },
    { title: 'Record, listen, revise', label: 'PERFORMANCE', text: 'A phone recording reveals timing, tone and transitions you may miss while playing. Choose one specific thing to improve per take and keep the best version.', visual: 'TAKE 1 → LISTEN → REFINE', visualNote: 'one change each pass', practice: 'Record one uninterrupted performance, then note one strength and one next step.' }
  ] }
};

const gradeNumber = Number(document.body.dataset.grade);
const grade = GRADE_DATA[gradeNumber];
if (grade) {
  document.title = `Grade ${gradeNumber}: ${grade.title} — Guitar Field Notes`;
  const course = document.querySelector('#gradeContent');
  const levelLinks = Array.from({ length: 9 }, (_, index) => {
    const number = index + 1;
    return `<a href="grade-${number}.html" class="${number === gradeNumber ? 'is-active' : ''}" ${number === gradeNumber ? 'aria-current="page"' : ''}><span>GRADE</span><b>${number}</b></a>`;
  }).join('');
  const lessonCards = grade.lessons.map((lesson, index) => {
    const chordRoot = lesson.chord?.replace(/m$/, '');
    const chordQuality = lesson.chord?.endsWith('m') ? 'minor' : 'major';
    const chordLink = lesson.chord ? `<a href="../chords/detail.html?root=${chordRoot}&quality=${chordQuality}">Open ${lesson.chord} chord guide ↗</a>` : '';
    return `<article class="lesson-card"><div><span class="lesson-index">${String(index + 1).padStart(2, '0')} / ${lesson.label}</span><h3>${lesson.title}</h3><p>${lesson.text}</p><span class="lesson-practice"><b>TRY IT:</b> ${lesson.practice}</span>${chordLink}</div><div class="lesson-visual"><strong>${lesson.visual.replaceAll('\n', '<br>')}</strong><small>${lesson.visualNote}</small></div></article>`;
  }).join('');
  const previous = gradeNumber > 1 ? `<a href="grade-${gradeNumber - 1}.html">← Grade ${gradeNumber - 1}</a>` : '<a hidden></a>';
  const next = gradeNumber < 9 ? `<a href="grade-${gradeNumber + 1}.html">Grade ${gradeNumber + 1} →</a>` : '<a href="../index.html#levels">Back to all grades ↑</a>';
  course.innerHTML = `<div class="lesson-topline"><a href="../index.html#levels">← ALL GRADES</a><a href="../chords/index.html">CHORD LIBRARY ↗</a></div><section class="lesson-hero"><div><span class="grade-stamp"><i></i>${grade.level} · GRADE ${gradeNumber}</span><h1>${grade.title}<br><em>one clear step at a time.</em></h1><p>${grade.subtitle}</p></div><div class="lesson-hero-art"><div><div class="grade-art-title">GUITAR FIELD NOTES / ${String(gradeNumber).padStart(2, '0')}</div><div class="grade-art-main">${grade.title}</div><div class="grade-art-sub">${grade.outcomes[0]} · ${grade.outcomes[1]}</div></div></div></section><nav class="grade-rail" aria-label="Course grades">${levelLinks}</nav><div class="outcomes-band"><strong>By the end, you can</strong><div class="outcome-list">${grade.outcomes.map((outcome) => `<span>${outcome}</span>`).join('')}</div></div><div class="grade-section-heading"><h2>Lessons in this grade</h2><span>${grade.lessons.length} STUDY UNITS</span></div><section class="lesson-cards">${lessonCards}</section><aside class="grade-practice"><div><h3>Make it stick</h3><p>Practise slowly, listen for clean notes, and revisit the chord library whenever a shape needs a closer look.</p></div><a href="../index.html#practice">Open practice tools ↗</a></aside><nav class="grade-pagination" aria-label="Previous and next grade">${previous}${next}</nav>`;
}